sudo: false

language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - 8.0

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  - SYMFONY_VERSION="^4.4"
  - SYMFONY_VERSION="^5.0"
  - SYMFONY_VERSION="^5.1"
  - SYMFONY_VERSION="^5.2"

matrix:
  fast_finish: true

  exclude:
#        - php: 7.0
#          env: SYMFONY_VERSION="^4.0"


before_install:
  - composer self-update
  - if [ "${SYMFONY_VERSION}" != "" ]; then composer require --no-update "symfony/symfony:${SYMFONY_VERSION}"; fi;

install:
  - composer update ${COMPOSER_FLAGS} --prefer-source

script:
  - vendor/bin/phpunit --colors
